openapi: 3.0.1
info:
  title: Working Group TWO
  description: Working Group Two REST APIs
  contact:
    email: wgtwo@wgtwo.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  version: 1.0.0
externalDocs:
  description: See docs.wgtwo.com
  url: 'https://docs.wgtwo.com'
servers:
  - url: 'https://api.wgtwo.com'
tags:
  - name: Subscription Profile
    description: Provision services for subscribers
    externalDocs:
      description: Find out more
      url: 'https://docs.wgtwo.com'
paths:
  /subscription/v1/msisdn/{msisdn}:
    get:
      tags:
        - Subscription Profile
      parameters:
        - name: msisdn
          in: path
          description: Phone number formatted as e.164 without + prefix
          required: true
          schema:
            type: string
            example: 4799990000
      summary: Get information about subscription
      operationId: getSubscription
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '405':
          description: Invalid input
          content: {}

  /provision/v1/activate:
    post:
      tags:
        - Subscription Profile
      summary: New user signs up
      operationId: activate.sim
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - iccid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                iccid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              iccid: "2420198416000015720"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'

  /provision/v1/block:
    post:
      tags:
        - Subscription Profile
      summary: Block SIM
      operationId: block.sim
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'

  /provision/v1/changesim:
    post:
      tags:
        - Subscription Profile
      summary: Change SIM
      operationId: change.sim
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - newIccid
                - oldIccid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                newIccid:
                  type: string
                oldIccid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              oldIccid: "2420198416000015720"
              newIccid: "2420198412148748973"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'

  /provision/v1/disengagesim:
    post:
      tags:
        - Subscription Profile
      summary: Disengage SIM
      operationId: disengage.sim
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - iccid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                iccid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              iccid: "2420198416000015720"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'

  /provision/v1/changemsisdn:
    post:
      tags:
        - Subscription Profile
      summary: Change MSISDN
      operationId: change.msisdn
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - msisdn
                - newMsisdn
                - userid
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                newMsisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              iccid: "2420198416000015720"
              msisdn: "46737678218"
              newMsisdn: "46737678200"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'

  /provision/v1/terminate:
    post:
      tags:
        - Subscription Profile
      summary: Terminate
      operationId: terminate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'

  /provision/v1/unblock:
    post:
      tags:
        - Subscription Profile
      summary: Unblock SIM
      operationId: unblock.sim
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - msisdn
                - userid
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
                userid:
                  type: string
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
              userid: "abcdefghijklm"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'

  /provision/v1/update:
    post:
      tags:
        - Subscription Profile
      summary: Update service
      operationId: updateService
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSubscriptionRequest'
            examples:
              enable-roaming:
                value:
                  bssid: "operator_name"
                  service:
                    name: ROAMING_DATA
                    action: ADD
                  msisdn: 4799990000
                  userid: my-user-id
              enable-user-tokens:
                value:
                  bssid: "operator_name"
                  service:
                    name: API_ACCESS_TO_OWN_SUBSCRIPTION
                    action: ADD
                  msisdn: 4799990000
                  userid: my-user-id
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
        '405':
          description: Invalid input
          content: {}
  /provision/v1/refreshprofile:
    post:
      tags:
        - Subscription Profile
      summary: Refresh profile
      operationId: refresh
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - bssid
                - msisdn
              properties:
                bssid:
                  type: string
                msisdn:
                  type: string
            example:
              bssid: "operator_name"
              msisdn: "46737678218"
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateSubscriptionResponse'
components:
  schemas:
    UpdateSubscriptionRequest:
      type: object
      required:
        - bssid
        - service
        - msisdn
        - userid
      properties:
        bssid:
          type: string
        service:
          type: object
          required:
            - name
            - action
          properties:
            name:
              type: string
              enum:
                - DATA
                - DATA_HIGHSPEED
                - DATA_TETHERING
                - MMS_IN
                - MMS_OUT
                - ROAMING
                - ROAMING_DATA
                - SMS_IN
                - SMS_OUT
                - SMS_OUT_INTER
                - SMS_PREMIUM
                - VOICE_CALLFORWARD
                - VOICE_CALLWAITING
                - VOICE_IN
                - VOICE_MISSED_CALL_ALERT
                - VOICE_OUT
                - VOICE_OUT_INTER
                - VOICE_PREMIUM
                - VOICE_VOICEMAIL
                - VOICE_VOLTE
                - VOICE_VOWIFI
                - VOICEMAIL_DISABLE_NOTIFICATION
              example: ROAMING_DATA
            action:
              type: string
              enum:
                - ADD
                - REMOVE
              example: ADD
            configuration:
              type: object
        msisdn:
          type: string
          example: '4799990000'
        userid:
          type: string
    UpdateSubscriptionResponse:
      type: object
      properties:
        requestid:
          type: string
    Subscription:
      type: object
      properties:
        id:
          type: integer
        msisdn:
          type: string
          example: '4799990000'
        active:
          type: boolean
          example: true
        userId:
          type: string
        bss:
          type: string
        simcards:
          type: array
          items:
            type: object
            properties:
              imsis:
                type: array
                items:
                  type: string
                  example:
                    - (...)001
                    - (...)002
              iccid:
                type: string
              bss:
                type: string
              created:
                type: string
                format: date-time
              lastModified:
                type: string
                format: date-time
        services:
          type: object
          additionalProperties:
            type: object
          example:
            SERVICE_A: {}
            SERVICE_B:
              some: config
        created:
          type: string
          format: date-time
        lastModified:
          type: string
          format: date-time
        imsi:
          type: string
        iccid:
          type: string
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://id.wgtwo.com/oauth2/token
          scopes:
            subscription.read: Read subscription information
            subscription.write: Update subscription
    operatorKey:
      type: http
      scheme: basic
      description: API key provided by Working Group Two
security:
  - operatorKey: []
  - OAuth2:
      - subscription.read
      - subscription.write
